### ISSUE TITLE
`mix test` fails with "module :eqc_component is not loaded and could not be found"

### ISSUE THREAD

**Issue by DNNX** [Quviq/eqc_ex#8]
Hello,

I'm trying to use the library and having problems running tests.

I cloned the repo, ran `mix eqc.install --mini` (not sure if it's needed) and then `mix test`. The test command failed with the following compile error:

```
$ mix test
** (CompileError) test/comp_eqc.exs:4: module :eqc_component is not loaded and could not be found
    (eqc_ex) expanding macro: EQC.Component.__using__/1
    test/comp_eqc.exs:4: Comp_eqc (module)
    (elixir) expanding macro: Kernel.use/1
    test/comp_eqc.exs:4: Comp_eqc (module)
    (elixir) lib/code.ex:370: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:57: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5
```

What am I doing wrong?

**Comment by ThomasArts** [comment]
Try adding it to your dependencies in mix.exs.
